import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Apex Catalyst",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <head>
        <link rel="icon" href="/logo.png" type="image/png" />
        {/* Optional: Add metadata here too */}
        <title>Apex Catalyst</title>
        <meta name="description" content="Empowering your business with intelligent design, smart automation, and digital excellence." />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <div className="relative z-50 pointer-events-auto">
          <Header />
        </div>
        {children}
        <Footer />  
      </body>
    </html>
  );
}
